import { Game } from '../types';

export const GAMES: Record<string, Game> = {
  chess: {
    id: 'chess',
    name: 'Chess Reborn',
    description: 'Experience the classic game of kings with tactical cyber aesthetics',
    rules: 'Capture the opponent\'s King or checkmate them to win.',
    icon: '👑',
    difficulty: 'hard',
    category: 'classic',
    boardSize: 8,
  },
  sudoku: {
    id: 'sudoku',
    name: 'Neon Sudoku',
    description: 'Master the logic of the 9x9 grid with procedurally generated puzzles',
    rules: 'Fill the grid so that every row, column, and 3x3 block contains digits 1-9.',
    icon: '🧩',
    difficulty: 'medium',
    category: 'classic',
    boardSize: 9,
    isSinglePlayer: true,
  },
  minesweeper: {
    id: 'minesweeper',
    name: 'DATA_CLEANER.SYS',
    description: 'Decrypt the corrupted grid sectors. Detect and isolate hidden malware nodes using logic diagnostics before they compromise the core system.',
    rules: 'Scan cells to reveal numbers showing adjacent malware nodes. Mark suspect malware grids with FLAG. Do not click mines!',
    icon: '💣',
    difficulty: 'easy',
    category: 'classic',
    boardSize: 9,
    isSinglePlayer: true,
  },
  2048: {
    id: '2048',
    name: 'NEON_OVERLOAD_2048',
    description: 'Merge identical data packets to compress and upgrade your system memory. Slide the grid and reach the ultimate 2048 main cluster.',
    rules: 'Slide tiles in 4 directions. When two identical values touch, they merge into one doubled value. Reach the 2048 tile!',
    icon: '⚡',
    difficulty: 'medium',
    category: 'classic',
    boardSize: 4,
    isSinglePlayer: true,
  },
  solitaire: {
    id: 'solitaire',
    name: 'STACK_PROTOCOLS',
    description: 'Deconstruct and reorganize chaotic data streams into perfect numerical stacks. The definitive digital card sorting simulation.',
    rules: 'Build foundations Ace to King by suit (H, D, S, C). Arrange tableau columns descending in alternating suit colors.',
    icon: '🃏',
    difficulty: 'medium',
    category: 'classic',
    boardSize: 7,
    isSinglePlayer: true,
  },
  xo: {
    id: 'xo',
    name: 'Classic X-O',
    description: 'The timeless 3x3 Tic-Tac-Toe game',
    rules: 'Get 3 of your symbols in a row',
    icon: '⭕',
    difficulty: 'easy',
    category: 'classic',
    boardSize: 3,
  },
  pyramid: {
    id: 'pyramid',
    name: 'Pyramid Tic-Tac-Toe',
    description: 'Play on a pyramid-shaped board',
    rules: 'Form 3-in-a-row on pyramid',
    icon: '🔺',
    difficulty: 'medium',
    category: 'variant',
    boardSize: 3,
  },
  fivebyfive: {
    id: 'fivebyfive',
    name: '5x5 Tic-Tac-Toe',
    description: 'Extended 5x5 grid gameplay',
    rules: 'Get 3-in-a-row on larger board',
    icon: '📊',
    difficulty: 'medium',
    category: 'variant',
    boardSize: 5,
  },
  fourbyfour: {
    id: 'fourbyfour',
    name: '4x4 Tic-Tac-Toe',
    description: 'Strategic 4x4 with moving pieces',
    rules: 'Get 4 in a row',
    icon: '🎲',
    difficulty: 'hard',
    category: 'variant',
    boardSize: 4,
  },
  ultimate: {
    id: 'ultimate',
    name: 'Ultimate Tic-Tac-Toe',
    description: '9 mini-boards in one',
    rules: 'Win mini-boards to control main board',
    icon: '🌐',
    difficulty: 'hard',
    category: 'advanced',
    boardSize: 3,
  },
  connectfour: {
    id: 'connectfour',
    name: 'Four-in-a-Row',
    description: 'Drop pieces to get 4 in a row',
    rules: 'Gravity-based gameplay',
    icon: '🔴',
    difficulty: 'medium',
    category: 'classic',
    boardSize: 7,
  },
  word: {
    id: 'word',
    name: 'Word Tic-Tac-Toe',
    description: 'Form valid 3-letter words',
    rules: 'Place letters to form words',
    icon: '📝',
    difficulty: 'hard',
    category: 'variant',
    boardSize: 3,
  },
  numerical: {
    id: 'numerical',
    name: 'Numerical Tic-Tac-Toe',
    description: 'Use numbers (odd/even)',
    rules: 'Sum of 3 numbers wins',
    icon: '🔢',
    difficulty: 'hard',
    category: 'variant',
    boardSize: 3,
  },
  misere: {
    id: 'misere',
    name: 'Misère Tic-Tac-Toe',
    description: 'Reverse rules - avoid 3-in-a-row',
    rules: 'Whoever gets 3-in-a-row LOSES',
    icon: '🔄',
    difficulty: 'hard',
    category: 'variant',
    boardSize: 3,
  },
  obstacles: {
    id: 'obstacles',
    name: 'Obstacles Tic-Tac-Toe',
    description: 'Board with blocked cells',
    rules: 'Navigate around obstacles',
    icon: '🚧',
    difficulty: 'medium',
    category: 'variant',
    boardSize: 5,
  },
  infinity: {
    id: 'infinity',
    name: 'Infinity Tic-Tac-Toe',
    description: 'Board expands infinitely',
    rules: 'Get 3-in-a-row on growing board',
    icon: '♾️',
    difficulty: 'hard',
    category: 'advanced',
    boardSize: 5,
  },
  diamond: {
    id: 'diamond',
    name: 'Diamond Tic-Tac-Toe',
    description: 'Diamond-shaped board',
    rules: 'Form 3-in-a-row on diamond',
    icon: '💎',
    difficulty: 'medium',
    category: 'variant',
    boardSize: 5,
  },
  memory: {
    id: 'memory',
    name: 'Memory Tic-Tac-Toe',
    description: 'Positions hidden after placement',
    rules: 'Remember where pieces are',
    icon: '🧠',
    difficulty: 'hard',
    category: 'advanced',
    boardSize: 4,
  },
  sus: {
    id: 'sus',
    name: 'SUS Game',
    description: 'Form S-U-S sequences',
    rules: 'Score by completing patterns',
    icon: '📮',
    difficulty: 'medium',
    category: 'variant',
    boardSize: 5,
  },
  snakesladders: {
    id: 'snakesladders',
    name: 'SNAKES & LADDERS',
    description: 'Roll the simulation die to navigate the neural grid. Climb logic ladders and bypass malicious snake vectors to reach node 100 first.',
    rules: 'Roll a 1-6 die to move. Land on a ladder base to climb up, land on a snake head to slide down. First player to land exactly on cell 100 wins!',
    icon: '🐍',
    difficulty: 'easy',
    category: 'party',
    boardSize: 10,
  },
};
